# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`

# example_test_data_ratio: 0.2
# example_num_train_iter: 10000
# example_learning_rate: 0.01

hktvmall_home_url: 'https://www.hktvmall.com/hktv/zh/supermarket'

product_by_method_catcode_url: "https://www.hktvmall.com/hktv/zh/ajax/search_products?query=%22%22%3A%3Acategory%3A{}%3Acategory{}%3A{}&pageType=searchResult&categoryCode={}"

hktvmall_cat_product_url: "https://www.hktvmall.com/hktv/zh/ajax/search_products?query=%22%22%3Arelevance%3Acategory%3A{}%3Astreet%3Amain%3A&pageSize={}&pageType=searchResult&categoryCode={}"

hktvmall_product_comment_url: "https://www.hktvmall.com/hktv/zh/ajax/get_pdp_product_reviews?productCode={}&currentPage=1&reviewType=all&pageSize={}"
hktvmall_category_diction_url: 'https://www.hktvmall.com/hktv/zh/main/category-directory'

hktvmall_catagory_code:
  supermarket: BB01000001021
  babyproducts: BB01000026191
  beautynhealth: BB09000008021
  deals: BB08000010881
  disneyproducts: BB17000000261
  homenfamily: BB03000001681
  housewares: BB10000000011
  insurancenfinance: BB16000000211
  personalcarenhealth: BB09000008011
  sportsntrip: BB03000021011
  switchgames: BB15000002161
  toysnbooks: BB10000003161

hktvmall_browse_method:
  discount: PromotionDifference
  hotpicks: HotPickOrder

hktv_mall_page_size_list:
  - 100
  - 200
  - 500
  - 1000
